const COLORS = {
    DEFAULT_BACKGROUND: '#00AA13',
    DEFAULT_TEXT: '#929292',
    WHITE: '#fff',
    BUTTON_AUTH_COLOR: '#2F4F4F',
    CHOOSED_COLOR: '#FF7700',
    DANGEROUS: '#FF450',

    /**ADMIN */
    BACKGROUND_ADMIN: '#008080'
}

exports.COLORS = COLORS;