export const PARAMS_CONSTANT = {
    SOGHE: 'SOGHE',
    NHIENLIEU: 'NHIENLIEU',
    MUCTIEUTHUNHIENLIEU: 'MUCTIEUTHUNHIENLIEU',
    TRUYENDONG: 'TRUYENDONG',
    TINHNANG: 'TINHNANG',
    GIAYTOTHUEXE: 'GIAYTOTHUEXE',
}